
package com.nissanusa.www.VehicleInformation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.vehicleinfo.webservices.xsd.VehicleInformationRequestType;
import com.vehicleinfo.webservices.xsd.VehicleInformationResponseType;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleInformationServiceImplServicePortType", targetNamespace = "http://www.nissanusa.com/VehicleInformation/")
@XmlSeeAlso({
	com.nissanusa.www.VehicleInformation.ObjectFactory.class,
    com.vehicleinfo.vo.xsd.ObjectFactory.class,
    com.vehicleinfo.webservices.xsd.ObjectFactory.class
})
public interface VehicleInformationServiceImplServicePortType {


    /**
     * 
     * @param regParams
     * @return
     *     returns com.vehicleinfo.webservices.xsd.VehicleInformationResponseType
     */
    @WebMethod(action = "urn:getVehicleInformation")
    @WebResult(targetNamespace = "http://www.nissanusa.com/VehicleInformation/")
    @RequestWrapper(localName = "getVehicleInformation", targetNamespace = "http://www.nissanusa.com/VehicleInformation/", className = "com.nissanusa.vehicleinformation.GetVehicleInformation")
    @ResponseWrapper(localName = "getVehicleInformationResponse", targetNamespace = "http://www.nissanusa.com/VehicleInformation/", className = "com.nissanusa.vehicleinformation.GetVehicleInformationResponse")
    public VehicleInformationResponseType getVehicleInformation(
        @WebParam(name = "regParams", targetNamespace = "http://www.nissanusa.com/VehicleInformation/")
        VehicleInformationRequestType regParams);

}
