
package com.nissanusa.www.VehicleInformation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleInformationServiceImplService", targetNamespace = "http://www.nissanusa.com/VehicleInformation/", wsdlLocation = "http://dmgtws.na.nissan.biz/axis2VinLookUp/services/VehicleInformationServiceImplService?wsdl")
public class VehicleInformationServiceImplService
    extends Service
{

    private final static URL VEHICLEINFORMATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLEINFORMATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VEHICLEINFORMATIONSERVICEIMPLSERVICE_QNAME = new QName("http://www.nissanusa.com/VehicleInformation/", "VehicleInformationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dmgtws.na.nissan.biz/axis2VinLookUp/services/VehicleInformationServiceImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLEINFORMATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VEHICLEINFORMATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public VehicleInformationServiceImplService() {
        super(__getWsdlLocation(), VEHICLEINFORMATIONSERVICEIMPLSERVICE_QNAME);
    }

    public VehicleInformationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLEINFORMATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public VehicleInformationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VEHICLEINFORMATIONSERVICEIMPLSERVICE_QNAME);
    }

    public VehicleInformationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLEINFORMATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public VehicleInformationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleInformationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleInformationServiceImplServicePortType
     */
    @WebEndpoint(name = "VehicleInformationServiceImplServiceHttpSoap11Endpoint")
    public VehicleInformationServiceImplServicePortType getVehicleInformationServiceImplServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://www.nissanusa.com/VehicleInformation/", "VehicleInformationServiceImplServiceHttpSoap11Endpoint"), VehicleInformationServiceImplServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleInformationServiceImplServicePortType
     */
    @WebEndpoint(name = "VehicleInformationServiceImplServiceHttpSoap11Endpoint")
    public VehicleInformationServiceImplServicePortType getVehicleInformationServiceImplServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nissanusa.com/VehicleInformation/", "VehicleInformationServiceImplServiceHttpSoap11Endpoint"), VehicleInformationServiceImplServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLEINFORMATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VEHICLEINFORMATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return VEHICLEINFORMATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
